# Generated by Django 4.0.6 on 2023-08-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.TextField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
