# Generated by Django 4.0.6 on 2023-08-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_event_activity_alter_event_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(default='', max_length=100),
        ),
    ]
