# Generated by Django 4.0.6 on 2023-08-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_event_user_alter_register_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='password1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='password2',
            field=models.CharField(max_length=100),
        ),
    ]
