# Generated by Django 4.0.6 on 2023-08-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_event_user_alter_event_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
