# Generated by Django 4.2.5 on 2023-09-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_event_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'permissions': [('add_choice', 'Can add a choice to a poll')]},
        ),
    ]
