# Generated by Django 4.2.5 on 2023-09-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_register_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'permissions': [('add_choice', 'email')]},
        ),
    ]
