# Generated by Django 4.2.5 on 2024-01-06 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_event_adde_date_event_completed_event_due_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='adde_date',
        ),
        migrations.AddField(
            model_name='event',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
